apiVersion: v1
kind: Pod
metadata:
  name: kyverno-test-allow
  namespace: devsecops
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        allowPrivilegeEscalation: false